### ISSUE TITLE
Pretty print single commit linter outputs

### ISSUE THREAD

**Issue by jiviteshjain** [MLH-Fellowship/git-lint-branch#10]
With multiple linters producing output per commit, the output becomes hard to read. 

- [x] A `--no-verbose` or similar option should silence help messages.
- [x] The commit data should include the commit message title and be printed only once per commit, with separators.
- [x] Color code according to severity

**Comment by avik-pal** [comment]
#16 addresses Color Codes.

**Comment by jiviteshjain** [comment]
#18 addresses this
